package output

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/zcube/gitversion-go/internal/rx"
)

// 원본 GitVersion.Output/AssemblyInfo/*, WixUpdater/* 대응.

const assemblyHeader = `//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------
`

// findRecursive 는 root 아래에서 match 에 맞는 파일을 재귀 탐색한다(숨김 디렉터리 제외).
func findRecursive(root string, match func(path string) bool) []string {
	var out []string
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if path != root && strings.HasPrefix(d.Name(), ".") {
				return filepath.SkipDir
			}
			return nil
		}
		if match(path) {
			out = append(out, path)
		}
		return nil
	})
	sort.Strings(out)
	return out
}

func resolveTargets(workDir string, files []string, match func(path string) bool) []string {
	if len(files) == 0 {
		return findRecursive(workDir, match)
	}
	out := make([]string, 0, len(files))
	for _, f := range files {
		out = append(out, filepath.Join(workDir, f))
	}
	return out
}

// UpdateAssemblyInfo 는 AssemblyInfo 파일들을 갱신(없으면 ensure 시 생성)한다.
func UpdateAssemblyInfo(vars *VersionVariables, workDir string, files []string, ensure bool) ([]string, error) {
	targets := resolveTargets(workDir, files, func(p string) bool {
		switch strings.ToLower(filepath.Base(p)) {
		case "assemblyinfo.cs", "assemblyinfo.vb", "assemblyinfo.fs":
			return true
		}
		return false
	})

	var updated []string
	for _, path := range targets {
		if _, err := os.Stat(path); err == nil {
			content, err := os.ReadFile(path)
			if err != nil {
				return nil, fmt.Errorf("파일 읽기 실패 %s: %w", path, err)
			}
			out := replaceAssemblyAttributes(string(content), vars)
			if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
				return nil, err
			}
			updated = append(updated, path)
		} else if ensure {
			content := createAssemblyInfo(path, vars)
			_ = os.MkdirAll(filepath.Dir(path), 0o755)
			if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
				return nil, err
			}
			updated = append(updated, path)
		}
	}
	return updated, nil
}

func replaceAssemblyAttributes(content string, vars *VersionVariables) string {
	replaceAttr := func(text, attr, value string) string {
		re := rx.MustCompile(`(` + attr + `\s*\(\s*")[^"]*("\s*\))`)
		return re.ReplaceAllFunc(text, func(m *rx.Match) string {
			g1, _ := m.Group(1)
			g2, _ := m.Group(2)
			return g1 + value + g2
		})
	}
	out := content
	out = replaceAttr(out, "AssemblyFileVersion", vars.AssemblySemFileVer)
	out = replaceAttr(out, "AssemblyInformationalVersion", vars.InformationalVersion)
	out = replaceAttr(out, "AssemblyVersion", vars.AssemblySemVer)
	return out
}

func createAssemblyInfo(path string, vars *VersionVariables) string {
	ext := strings.ToLower(strings.TrimPrefix(filepath.Ext(path), "."))
	fv, av, iv := vars.AssemblySemFileVer, vars.AssemblySemVer, vars.InformationalVersion
	switch ext {
	case "vb":
		return assemblyHeader + "\nImports System.Reflection\n\n" +
			fmt.Sprintf("<Assembly: AssemblyFileVersion(\"%s\")>\n", fv) +
			fmt.Sprintf("<Assembly: AssemblyVersion(\"%s\")>\n", av) +
			fmt.Sprintf("<Assembly: AssemblyInformationalVersion(\"%s\")>\n", iv)
	case "fs":
		return assemblyHeader + "\nnamespace AssemblyInfo\n\nopen System.Reflection\n\n" +
			fmt.Sprintf("[<assembly: AssemblyFileVersion(\"%s\")>]\n", fv) +
			fmt.Sprintf("[<assembly: AssemblyVersion(\"%s\")>]\n", av) +
			fmt.Sprintf("[<assembly: AssemblyInformationalVersion(\"%s\")>]\n", iv) +
			"do ()\n"
	default:
		return assemblyHeader + "\nusing System.Reflection;\n\n" +
			fmt.Sprintf("[assembly: AssemblyFileVersion(\"%s\")]\n", fv) +
			fmt.Sprintf("[assembly: AssemblyVersion(\"%s\")]\n", av) +
			fmt.Sprintf("[assembly: AssemblyInformationalVersion(\"%s\")]\n", iv)
	}
}

var projectElements = []string{"AssemblyVersion", "FileVersion", "InformationalVersion", "Version"}

func projectElementValue(vars *VersionVariables, elem string) string {
	switch elem {
	case "AssemblyVersion":
		return vars.AssemblySemVer
	case "FileVersion":
		return vars.AssemblySemFileVer
	case "InformationalVersion":
		return vars.InformationalVersion
	default:
		return vars.SemVer
	}
}

// UpdateProjectFiles 는 .csproj/.vbproj/.fsproj 의 버전 요소를 갱신한다.
func UpdateProjectFiles(vars *VersionVariables, workDir string, files []string) ([]string, error) {
	targets := resolveTargets(workDir, files, func(p string) bool {
		switch strings.ToLower(strings.TrimPrefix(filepath.Ext(p), ".")) {
		case "csproj", "vbproj", "fsproj":
			return true
		}
		return false
	})

	var updated []string
	for _, path := range targets {
		if _, err := os.Stat(path); err != nil {
			continue
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("파일 읽기 실패 %s: %w", path, err)
		}
		out := replaceProjectElements(string(content), vars)
		if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
			return nil, err
		}
		updated = append(updated, path)
	}
	return updated, nil
}

// replaceProjectElements 는 존재하는 버전 요소 값을 갱신하고, 없는 요소는 첫
// PropertyGroup 끝에 추가한다. 정규식 타깃 치환으로 주석/속성/들여쓰기를 보존한다.
func replaceProjectElements(content string, vars *VersionVariables) string {
	out := content
	existing := map[string]bool{}
	for _, elem := range projectElements {
		re := rx.MustCompile(`(<` + elem + `(?:\s[^>]*)?>)([^<]*)(</` + elem + `>)`)
		if _, ok := re.Find(out); ok {
			existing[elem] = true
			value := projectElementValue(vars, elem)
			out = re.ReplaceAllFunc(out, func(m *rx.Match) string {
				g1, _ := m.Group(1)
				g3, _ := m.Group(3)
				return g1 + value + g3
			})
		}
	}

	// 없는 요소를 첫 PropertyGroup 끝 앞에 삽입.
	var missing []string
	for _, elem := range projectElements {
		if !existing[elem] {
			missing = append(missing, elem)
		}
	}
	if len(missing) == 0 {
		return out
	}
	closeIdx := strings.Index(out, "</PropertyGroup>")
	if closeIdx < 0 {
		return out
	}
	// 닫는 태그의 들여쓰기를 포착하고 자식 들여쓰기는 +2칸으로 맞춘다.
	raw := out[:closeIdx]
	i := len(raw)
	for i > 0 && (raw[i-1] == ' ' || raw[i-1] == '\t') {
		i--
	}
	closeIndent := raw[i:]
	left := raw[:i]
	childIndent := closeIndent + "  "

	lines := make([]string, 0, len(missing))
	for _, elem := range missing {
		lines = append(lines, childIndent+fmt.Sprintf("<%s>%s</%s>", elem, projectElementValue(vars, elem), elem))
	}
	block := strings.Join(lines, "\n")
	if strings.HasSuffix(left, "\n") || left == "" {
		block = block + "\n" + closeIndent
	} else {
		block = "\n" + block + "\n" + closeIndent
	}
	return left + block + out[closeIdx:]
}

// UpdatePackageFiles 는 언어별 패키지 매니페스트의 버전 필드를 갱신한다.
func UpdatePackageFiles(vars *VersionVariables, workDir string, files []string) ([]string, error) {
	targets := resolveTargets(workDir, files, func(p string) bool {
		for _, c := range strings.Split(filepath.ToSlash(p), "/") {
			if c == "node_modules" || c == "vendor" || c == "target" {
				return false
			}
		}
		switch strings.ToLower(filepath.Base(p)) {
		case "package.json", "cargo.toml", "pyproject.toml":
			return true
		}
		return false
	})

	var updated []string
	for _, path := range targets {
		if _, err := os.Stat(path); err != nil {
			continue
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("파일 읽기 실패 %s: %w", path, err)
		}
		version := vars.SemVer
		var newContent string
		var ok bool
		switch strings.ToLower(filepath.Base(path)) {
		case "package.json":
			newContent, ok = updatePackageJSON(string(content), version)
		case "cargo.toml":
			newContent, ok = updateTOMLSection(string(content), version, "package")
		case "pyproject.toml":
			newContent, ok = updatePyproject(string(content), version)
		}
		if ok {
			if err := os.WriteFile(path, []byte(newContent), 0o644); err != nil {
				return nil, err
			}
			updated = append(updated, path)
		}
	}
	return updated, nil
}

var pkgJSONVersionRe = regexp.MustCompile(`("version"\s*:\s*")[^"]*(")`)

// updatePackageJSON 은 최상위 "version" 값을 갱신한다(포맷/키 순서 보존).
func updatePackageJSON(content, version string) (string, bool) {
	if !pkgJSONVersionRe.MatchString(content) {
		return "", false
	}
	replaced := false
	out := pkgJSONVersionRe.ReplaceAllStringFunc(content, func(m string) string {
		if replaced {
			return m
		}
		replaced = true
		sub := pkgJSONVersionRe.FindStringSubmatch(m)
		return sub[1] + version + sub[2]
	})
	return out, true
}

// updateTOMLSection 은 [section] 의 version = "..." 를 갱신한다(주석/포맷 보존).
func updateTOMLSection(content, version, section string) (string, bool) {
	lines := strings.Split(content, "\n")
	inSection := false
	headerRe := regexp.MustCompile(`^\s*\[([^\]]+)\]`)
	versionRe := regexp.MustCompile(`^(\s*version\s*=\s*")[^"]*(".*)$`)
	changed := false
	for i, line := range lines {
		if m := headerRe.FindStringSubmatch(line); m != nil {
			inSection = strings.TrimSpace(m[1]) == section
			continue
		}
		if inSection {
			if m := versionRe.FindStringSubmatch(line); m != nil {
				lines[i] = m[1] + version + m[2]
				changed = true
				inSection = false
			}
		}
	}
	if !changed {
		return "", false
	}
	return strings.Join(lines, "\n"), true
}

// updatePyproject 는 [project] 또는 [tool.poetry] 의 version 을 갱신한다.
func updatePyproject(content, version string) (string, bool) {
	if out, ok := updateTOMLSection(content, version, "project"); ok {
		return out, true
	}
	return updateTOMLSection(content, version, "tool.poetry")
}

// WriteWix 는 Wix 버전 파일(GitVersion_WixVersion.wxi)을 생성한다.
func WriteWix(vars *VersionVariables, workDir string) (string, error) {
	var b strings.Builder
	b.WriteString("\uFEFF") // UTF-8 BOM
	b.WriteString("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n")
	b.WriteString("<Include xmlns=\"http://schemas.microsoft.com/wix/2006/wi\">\n")
	m := vars.ToMap()
	for _, k := range SortedKeys(m) {
		b.WriteString(fmt.Sprintf("  <?define %s=\"%s\"?>\n", k, m[k]))
	}
	b.WriteString("</Include>")
	path := filepath.Join(workDir, "GitVersion_WixVersion.wxi")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
